CREATE TABLE h_units(
   id VARCHAR(255) NOT NULL,
   units CHAR(10) NOT NULL,
   descriptions VARCHAR(255) NOT NULL
);

CREATE TABLE h_times(
   id VARCHAR(10) NOT NULL,
   day INTEGER NOT NULL,
   weeks INTEGER NOT NULL,
   months INTEGER NOT NULL,
   quarter INTEGER NOT NULL,
   years INTEGER NOT NULL
);

CREATE TABLE h_keys(
   id VARCHAR(255) NOT NULL,
   h_unit_id VARCHAR(255) NOT NULL,
   descriptions VARCHAR(1000) NOT NULL
);
CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE table1(
field1 INTEGER PRIMARY KEY,
field2 VARCHAR NOT NULL
);

CREATE TABLE table2(
field12 FLOAT PRIMARY KEY,
field13 DATETIME NOT NULL
);

CREATE TABLE table1(
field1 BOOLEAN NOT NULL
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE asd(
dad VARCHAR
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE ccc(
dad CHAR
);

CREATE TABLE asd(
ddd BLOB NOT NULL,
bddd BLOB NOT NULL
);

CREATE TABLE table1(
   field1 BOOLEAN NOT NULL,
   field2 DECIMAL NOT NULL
);

CREATE TABLE table1(
   field1 VARCHAR NOT NULL,
   field2 INTEGER NOT NULL
);

CREATE TABLE sddd(
   xxx VARCHAR
);

