CREATE TABLE h_units(
   id VARCHAR(255) NOT NULL,
   units CHAR(10) NOT NULL,
   descriptions VARCHAR(255) NOT NULL
);

CREATE TABLE h_times(
   id VARCHAR(10) NOT NULL,
   day INTEGER NOT NULL,
   weeks INTEGER NOT NULL,
   months INTEGER NOT NULL,
   quarter INTEGER NOT NULL,
   years INTEGER NOT NULL
);

CREATE TABLE h_keys(
   id VARCHAR(255) NOT NULL,
   h_unit_id VARCHAR(255) NOT NULL,
   descriptions VARCHAR(1000) NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE asd(
   ddd BLOB NOT NULL,
   bddd BLOB NOT NULL
);

CREATE TABLE table1(
   field1 BLOB NOT NULL,
   field2 FLOAT NOT NULL
);

CREATE TABLE sas(
   dad VARCHAR
);

CREATE TABLE table1(
   field1 VARCHAR,
   field2 DOUBLE NOT NULL
);

CREATE TABLE Table2(
   field11 DATETIME NOT NULL,
   field12 DECIMAL NOT NULL
);

